# Empty and omitted keys will use default values
AuditEnabled: true
#WriteDirectory: out
OverwriteHistoricalAudits: true
Run: # must be all-lowercase
  - "kubernetes"
  # - "storage"
ServicePacks:
  Kubernetes:
    KubeConfig: 
    KubeContext:
    AuthorisedContainerRegistry: citihubprod.azurecr.io # required
    UnauthorisedContainerRegistry: docker.io # required
    ProbeImage: citihub/probr-probe
    ContainerRequiredDropCapabilities:
      - NET_RAW
    SystemNamespace: kube-system
    DashboardPodNamePrefix: kubernetes-dashboard
    # TODO: these exclusions are not being handled in the SP
    Probes: # allows this pack's probes to be disabled by name
      - Name: pod_security_policy
        Excluded: "out"
      - Name: iam
        Excluded: out
      - Name: general
        Excluded:
      - Name: container_registry_access
        Excluded: "out"
      - Name: internet_access
        Excluded: "out"
        Scenarios: # allows this probe's scenarios to be disabled using their probe tag value
          - Name: "1.0"
            Excluded: # "Excluded to demonstrate scenario exclusion option"
  Storage:
    Provider: Azure # if object OR required vars within it are omitted, pack will not be included
CloudProviders:
  Azure:
    TenantID: ""
    SubscriptionID: ""
    ClientID: ""
    ClientSecret: ""
    ManagementGroup:
    ResourceGroup: ProbrRG
    ResourceLocation: "westeurope"
    Identity:
      DefaultNamespaceAI:
      DefaultNamespaceAIB:
Tags: # allows user to create their own string of tag inclusions and/or exclusions
TagExclusions: # allows specific controls/scenarios to be disabled via a list of tags